version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdata/db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5438:5432'
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
  fe:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend/public:/public'
      - '/frontend/node_modules'
      - '/frontend/src'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    # command: yarn start
    stdin_open: true
    tty: true
volumes:
  pgdata:
