# Generated by Django 3.2.18 on 2023-02-19 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0002_candidate_position'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='party',
        #     name='agent',
        #     field=models.ForeignKey(blank=True, help_text='Agent in command', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
    ]
