# Generated by Django 3.2.18 on 2023-02-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_party_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='full_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Candidate first name'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Candidate last name'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_names',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Candidate other names'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr'), ('Mrs.', 'Mrs'), ('Miss', 'Miss'), ('Sr.', 'Sr'), ('Esqr.', 'Esqr')], max_length=255, null=True, verbose_name='Candidate title'),
        ),
    ]
