# Generated by Django 3.2.18 on 2023-02-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20230225_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='title',
        ),
        migrations.AddField(
            model_name='candidate',
            name='prefix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Candidate title'),
        ),
    ]
