# Generated by Django 3.2.18 on 2023-03-11 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('people', '0011_agent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='zone_ct',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'geo'), ('model', 'Nation')), models.Q(('app_label', 'geo'), ('model', 'Region')), models.Q(('app_label', 'geo'), ('model', 'Constituency')), models.Q(('app_label', 'geo'), ('model', 'Station')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_ct', to='contenttypes.contenttype'),
        ),
    ]
