# Generated by Django 3.2.18 on 2023-02-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='code',
        ),
    ]
