# Generated by Django 3.2.18 on 2023-02-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_remove_constituency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='code',
            field=models.CharField(default='-', max_length=25, verbose_name='Constituency code'),
            preserve_default=False,
        ),
    ]
