# Generated by Django 3.2.18 on 2023-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_station_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(max_length=25, null=True, verbose_name='Constituency code'),
        ),
    ]
