# Generated by Django 3.2.18 on 2023-03-02 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0004_alter_station_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent in command', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='region',
            field=models.ForeignKey(help_text='Region', on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='geo.region'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent in command', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent in command', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='nation',
            field=models.ForeignKey(help_text='Nation', on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='geo.nation'),
        ),
        migrations.AlterField(
            model_name='station',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent in command', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='station',
            name='constituency',
            field=models.ForeignKey(help_text='Constituency', on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='geo.constituency'),
        ),
    ]
