# Generated by Django 3.2.18 on 2023-03-07 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_party_agent'),
        ('geo', '0005_auto_20230302_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent in command', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='people.agent'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent in command', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nations', to='people.agent'),
        ),
        migrations.AlterField(
            model_name='region',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent in command', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='people.agent'),
        ),
        migrations.AlterField(
            model_name='station',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent in command', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='people.agent'),
        ),
    ]
