# Generated by Django 3.2.18 on 2023-03-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20230307_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='nation',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='region',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='station',
            name='agent',
        ),
    ]
