# Generated by Django 3.2.18 on 2023-02-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Station'), (2, 'Constituency'), (3, 'Region'), (4, 'National')], default=0, help_text='Election level'),
        ),
        migrations.AlterField(
            model_name='position',
            name='level',
            field=models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Station'), (2, 'Constituency'), (3, 'Region'), (4, 'National')], help_text='Geographic level of the position'),
        ),
    ]
