# Generated by Django 3.2.18 on 2023-02-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20230219_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Office / designation / title name')),
                ('level', models.CharField(choices=[('', 'Unassigned'), ('Parliamentary', 'Parliament'), ('Vice-President', 'Vice President'), ('President', 'President')], default='', max_length=255, verbose_name='Office level')),
            ],
            options={
                'db_table': 'poll_office',
            },
        ),
    ]
