# Generated by Django 3.2.18 on 2023-02-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_office_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='level',
            field=models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Station'), (2, 'Constituency'), (3, 'Region'), (4, 'National')], default=0, verbose_name='Office level'),
        ),
    ]
