# Generated by Django 3.2.18 on 2023-02-26 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_office_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='level',
        ),
        migrations.RemoveField(
            model_name='event',
            name='position',
        ),
        migrations.AddField(
            model_name='event',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Election office/level', null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.office'),
        ),
        migrations.AddField(
            model_name='position',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Office being contested', null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.office'),
        ),
        migrations.AlterField(
            model_name='office',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Office / designation / title'),
        ),
        migrations.AlterField(
            model_name='position',
            name='zone',
            field=models.IntegerField(blank=True, help_text='Zone ID based on the office', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('office', 'zone')},
        ),
        migrations.RemoveField(
            model_name='position',
            name='level',
        ),
    ]
