# Generated by Django 3.2.18 on 2023-02-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20230227_2149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='position',
            name='zone_id',
        ),
    ]
