# Generated by Django 3.2.18 on 2023-03-01 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('poll', '0008_auto_20230227_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='zone_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'geo'), ('model', 'Nation')), models.Q(('app_label', 'geo'), ('model', 'Constituency')), models.Q(('app_label', 'geo'), ('model', 'Region')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='position',
            name='zone_object_id',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
    ]
