# Generated by Django 3.2.18 on 2023-03-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20230301_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='zone_content_type',
            new_name='zone_ct',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='zone_object_id',
            new_name='zone_id',
        ),
    ]
