# Generated by Django 3.2.18 on 2023-03-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_auto_20230301_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='office',
        ),
    ]
