# Generated by Django 3.2.18 on 2023-03-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_party_agent'),
        ('poll', '0011_remove_position_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='party',
        ),
        migrations.RemoveField(
            model_name='result',
            name='position',
        ),
        migrations.RemoveField(
            model_name='result',
            name='result_sheet_url',
        ),
        migrations.AddField(
            model_name='result',
            name='candidate',
            field=models.ForeignKey(blank=True, default=None, help_text='Candidate', null=True, on_delete=django.db.models.deletion.CASCADE, to='people.candidate'),
        ),
        migrations.AddField(
            model_name='result',
            name='result_sheet',
            field=models.FileField(blank=True, default=None, help_text='Result verification sheet', null=True, upload_to='results/%Y/%m/%d'),
        ),
    ]
