# Generated by Django 3.2.18 on 2023-03-02 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20230302_0244'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0005_auto_20230302_0244'),
        ('poll', '0013_result_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Election office/level', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='poll.office'),
        ),
        migrations.AlterField(
            model_name='result',
            name='candidate',
            field=models.ForeignKey(blank=True, default=None, help_text='Candidate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='people.candidate'),
        ),
        migrations.AlterField(
            model_name='result',
            name='constituency_agent',
            field=models.ForeignKey(help_text='Constituency agent that recorded', on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result',
            name='station',
            field=models.ForeignKey(help_text='Polling Station', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='geo.station'),
        ),
        migrations.AlterField(
            model_name='resultapproval',
            name='approving_agent',
            field=models.ForeignKey(help_text='Agent that approved the result', on_delete=django.db.models.deletion.CASCADE, related_name='result_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
