# Generated by Django 3.2.18 on 2023-03-05 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0015_alter_result_constituency_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='constituency_agent',
        ),
        migrations.AddField(
            model_name='result',
            name='station_agent',
            field=models.ForeignKey(blank=True, default=None, help_text='Station agent that recorded the result', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL),
        ),
    ]
