# Generated by Django 3.2.18 on 2023-03-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0017_resultsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result_sheet',
            field=models.FileField(blank=True, default=None, help_text='Result verification sheet', null=True, upload_to='results%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='resultsheet',
            name='result_sheet',
            field=models.FileField(blank=True, default=None, help_text='Statement of poll and declaration of results', null=True, upload_to='results%Y%m%d'),
        ),
    ]
