# Generated by Django 3.2.18 on 2023-03-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_auto_20230307_0707'),
        ('poll', '0025_auto_20230311_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituencycollationsheet',
            name='constituency',
            field=models.ForeignKey(help_text='Constituency', on_delete=django.db.models.deletion.CASCADE, related_name='constituency_collation_sheets', to='geo.constituency'),
        ),
    ]
