# Generated by Django 3.2.18 on 2023-03-11 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_auto_20230307_0707'),
        ('poll', '0026_alter_constituencycollationsheet_constituency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituencycollationsheet',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='nationalcollationsheet',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='regionalcollationsheet',
            name='region',
        ),
        migrations.AddField(
            model_name='constituencycollationsheet',
            name='station',
            field=models.ForeignKey(blank=True, default=None, help_text='Station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constituency_collation_sheets', to='geo.station'),
        ),
        migrations.AddField(
            model_name='nationalcollationsheet',
            name='region',
            field=models.ForeignKey(blank=True, default=None, help_text='Region', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_collation_sheets', to='geo.region'),
        ),
        migrations.AddField(
            model_name='regionalcollationsheet',
            name='constituency',
            field=models.ForeignKey(blank=True, default=None, help_text='Constituency', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regional_collation_sheets', to='geo.constituency'),
        ),
        migrations.AlterField(
            model_name='stationcollationsheet',
            name='station',
            field=models.ForeignKey(blank=True, default=None, help_text='Polling Station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_collation_sheets', to='geo.station'),
        ),
    ]
