# Generated by Django 3.2.18 on 2023-03-11 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_alter_agent_zone_ct'),
        ('poll', '0027_auto_20230311_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituencycollationsheet',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='nationalcollationsheet',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='regionalcollationsheet',
            name='candidate',
        ),
        migrations.AddField(
            model_name='constituencycollationsheet',
            name='party',
            field=models.ForeignKey(blank=True, default=None, help_text='Party', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constituency_collation_sheets', to='people.party'),
        ),
        migrations.AddField(
            model_name='nationalcollationsheet',
            name='party',
            field=models.ForeignKey(blank=True, default=None, help_text='Party', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_collation_sheets', to='people.party'),
        ),
        migrations.AddField(
            model_name='regionalcollationsheet',
            name='party',
            field=models.ForeignKey(blank=True, default=None, help_text='Party', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regional_collation_sheets', to='people.party'),
        ),
    ]
