# Generated by Django 3.2.18 on 2023-03-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_auto_20230307_0707'),
        ('people', '0012_alter_agent_zone_ct'),
        ('poll', '0028_auto_20230311_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupernationalCollationSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(blank=True, help_text='Total number of votes', null=True, verbose_name='EC Summary Collation totals')),
                ('total_valid_votes', models.IntegerField(blank=True, help_text='Total number of valid votes', null=True, verbose_name='Collation total number of valid votes')),
                ('total_invalid_votes', models.IntegerField(blank=True, help_text='Total number of invalid votes', null=True, verbose_name='Collation total number of invalid votes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=35, null=True)),
                ('nation', models.ForeignKey(blank=True, default=None, help_text='Nation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supernational_collation_sheets', to='geo.nation')),
                ('party', models.ForeignKey(blank=True, default=None, help_text='Party', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supernational_collation_sheets', to='people.party')),
            ],
            options={
                'db_table': 'poll_supernational_collation_sheet',
            },
        ),
    ]
