# Generated by Django 3.2.18 on 2023-03-11 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('poll', '0029_supernationalcollationsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituencycollationsheet',
            name='zone_ct',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(models.Q(('app_label', 'geo'), ('model', 'Nation')), models.Q(('app_label', 'geo'), ('model', 'Constituency')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constituency_collation_zones', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='nationalcollationsheet',
            name='zone_ct',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(models.Q(('app_label', 'geo'), ('model', 'Nation')), models.Q(('app_label', 'geo'), ('model', 'Constituency')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='national_collation_zones', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='regionalcollationsheet',
            name='zone_ct',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(models.Q(('app_label', 'geo'), ('model', 'Nation')), models.Q(('app_label', 'geo'), ('model', 'Constituency')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_collation_zones', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stationcollationsheet',
            name='zone_ct',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(models.Q(('app_label', 'geo'), ('model', 'Nation')), models.Q(('app_label', 'geo'), ('model', 'Constituency')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_collation_zones', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='supernationalcollationsheet',
            name='zone_ct',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(models.Q(('app_label', 'geo'), ('model', 'Nation')), models.Q(('app_label', 'geo'), ('model', 'Constituency')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supernational_collation_zones', to='contenttypes.contenttype'),
        ),
    ]
