# Generated by Django 3.2.18 on 2023-03-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0030_auto_20230311_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituencycollationsheet',
            name='total_invalid_votes',
        ),
        migrations.RemoveField(
            model_name='constituencycollationsheet',
            name='total_valid_votes',
        ),
        migrations.RemoveField(
            model_name='nationalcollationsheet',
            name='total_invalid_votes',
        ),
        migrations.RemoveField(
            model_name='nationalcollationsheet',
            name='total_valid_votes',
        ),
        migrations.RemoveField(
            model_name='regionalcollationsheet',
            name='total_invalid_votes',
        ),
        migrations.RemoveField(
            model_name='regionalcollationsheet',
            name='total_valid_votes',
        ),
        migrations.RemoveField(
            model_name='stationcollationsheet',
            name='total_invalid_votes',
        ),
        migrations.RemoveField(
            model_name='stationcollationsheet',
            name='total_valid_votes',
        ),
        migrations.RemoveField(
            model_name='supernationalcollationsheet',
            name='total_invalid_votes',
        ),
        migrations.RemoveField(
            model_name='supernationalcollationsheet',
            name='total_valid_votes',
        ),
        migrations.AddField(
            model_name='constituencycollationsheet',
            name='total_votes_ec',
            field=models.IntegerField(blank=True, help_text='EC Collation number', null=True, verbose_name='EC Summary Collation totals'),
        ),
        migrations.AddField(
            model_name='nationalcollationsheet',
            name='total_votes_ec',
            field=models.IntegerField(blank=True, help_text='EC Collation number', null=True, verbose_name='EC Summary Collation totals'),
        ),
        migrations.AddField(
            model_name='regionalcollationsheet',
            name='total_votes_ec',
            field=models.IntegerField(blank=True, help_text='EC Collation number', null=True, verbose_name='EC Summary Collation totals'),
        ),
        migrations.AddField(
            model_name='stationcollationsheet',
            name='total_votes_ec',
            field=models.IntegerField(blank=True, help_text='EC Collation number', null=True, verbose_name='EC Summary Collation totals'),
        ),
        migrations.AddField(
            model_name='supernationalcollationsheet',
            name='total_votes_ec',
            field=models.IntegerField(blank=True, help_text='EC Collation number', null=True, verbose_name='EC Summary Collation totals'),
        ),
        migrations.AlterField(
            model_name='constituencycollationsheet',
            name='total_votes',
            field=models.IntegerField(blank=True, help_text='Total number of votes', null=True, verbose_name='Collation total number of valid votes'),
        ),
        migrations.AlterField(
            model_name='nationalcollationsheet',
            name='total_votes',
            field=models.IntegerField(blank=True, help_text='Total number of votes', null=True, verbose_name='Collation total number of valid votes'),
        ),
        migrations.AlterField(
            model_name='regionalcollationsheet',
            name='total_votes',
            field=models.IntegerField(blank=True, help_text='Total number of votes', null=True, verbose_name='Collation total number of valid votes'),
        ),
        migrations.AlterField(
            model_name='stationcollationsheet',
            name='total_votes',
            field=models.IntegerField(blank=True, help_text='Total number of votes', null=True, verbose_name='Collation total number of valid votes'),
        ),
        migrations.AlterField(
            model_name='supernationalcollationsheet',
            name='total_votes',
            field=models.IntegerField(blank=True, help_text='Total number of votes', null=True, verbose_name='Collation total number of valid votes'),
        ),
    ]
