# Generated by Django 3.2.18 on 2023-03-12 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_auto_20230307_0707'),
        ('people', '0012_alter_agent_zone_ct'),
        ('poll', '0031_auto_20230311_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentarySummarySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(blank=True, help_text='Total number of votes', null=True, verbose_name='Collation total number of valid votes')),
                ('total_votes', models.IntegerField(blank=True, help_text='EC Collation number', null=True, verbose_name='EC Summary Collation totals')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=35)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('candidate', models.OneToOneField(blank=True, default=None, help_text='Candidate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_summary_sheet', to='people.candidate')),
                ('constituency', models.OneToOneField(blank=True, default=None, help_text='Constituency', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_summary_sheet', to='geo.constituency')),
                ('position', models.OneToOneField(blank=True, default=True, help_text='Position', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_summary_sheet', to='poll.position')),
            ],
            options={
                'db_table': 'poll_parliamentary_summary_sheet',
            },
        ),
    ]
